server:
  port: 6266
  enableHTTPS: false

logger:
  level: verbose # debug, verbose, info, error
  filename: faucet.log

provider:
  name: insight # only insight now, with rawtx support (!)
  insight:
    url: http://devel.hz.udoidio.info:3001/api/
    timeout: 10000 # in milliseconds

storage:
  filename: wallet.db # path to data file
  compactionInterval: 300 # in seconds

faucet:
  withdrawal:
    max: 1000000 # in satoshi
  unspents:
    stockpile: 10 # for every type
    issueLowerBound: 5 # also for every type
    types:
      -
        name: '1' # name as string, important!
        preload: [100000]
      -
        name: '2'
        preload: [25000, 25000]
      -
        name: '3'
        preload: [100000, 50000, 10000]

wallet:
  network: testnet # network name from bitcore.Networks

  mnemonic: clever miracle diet judge simple clock party report replace ancient wrist era
  passphrase: my faucet
  addressesPoolSize: 10 # addresses pool size

  forceUnspentUpdate: 600 # in seconds
