server:
  port: 6266
  enableHTTPS: false

logger:
  level: verbose # debug, verbose, info, error
  filename: faucet.log

provider:
  name: cb-insight # https://github.com/dcousens/common-blockchain (only insight now)
  insight:
    url: https://test-insight.bitpay.com/api/

storage:
  filename: wallet.db # path to data file
  compactionInterval: 300 # in seconds

faucet:
  withdrawal:
    active: true
    max: 1000000 # in satoshi
  unspents:
    allow: true
    stockpile: 10 # for every type
    issueLowerBound: 50 # in percent
    types:
      -
        name: 1
        preload: [100000]
      -
        name: 2
        preload: [25000, 25000]
      -
        name: 3
        preload: [100000, 50000, 10000]

wallet:
  network: testnet # network name from bitcore.Networks

  mnemonic: clever miracle diet judge simple clock party report replace ancient wrist era
  passphrase: my faucet
  addressesPoolSize: 10 # addresses pool size

  refreshInterval: 120 # every N seconds collect new unspents for issuance and withdrawal
