server:
  port: 6266
  enableHTTPS: false

logger:
  level: verbose # debug, verbose, info, error
  filename: faucet.log

provider:
  name: insight # only insight now
  insight:
    url: http://devel.hz.udoidio.info:3001/api/
    timeout: 10000 # in milliseconds

storage:
  filename: wallet.db # path to data file
  compactionInterval: 300 # in seconds

faucet:
  withdrawal:
    active: true
    max: 1000000 # in satoshi
  unspents:
    allow: true
    stockpile: 5 # for every type
    issueLowerBound: 50 # in percent
    types:
      -
        name: 1
        preload: [100000]
      -
        name: 2
        preload: [25000, 25000]
      -
        name: 3
        preload: [100000, 50000, 10000]

wallet:
  network: testnet # network name from bitcore.Networks

  mnemonic: hello female leader core filter robot rare purity laugh trim rug theme
  passphrase:
  addressesPoolSize: 3 # addresses pool size
